### ISSUE TITLE
New tab sometimes opens in background

### ISSUE THREAD

**Issue by orschiro** [orschiro/tsrlt-chrome-extension#7]
Occasionally new tabs open in background and the current tab remains focused. 

@Bibernull any ideas on this one? 

Thankfully,

Robert

**Comment by Bibernull** [comment]
Not sure what would cause this, but more info would be useful.
Is it certain this extension is causing it?

**Comment by orschiro** [comment]
> Not sure what would cause this, but more info would be useful.

Let me try to debug this further! 

> Is it certain this extension is causing it?

It occurred with one of the recent releases. 

I will test with `Switch to last focused tab on close` disabled. 

~ Robert

**Comment by orschiro** [comment]
Dear @Bibernull,

As far as I can tell, the problem occurs with `Switch to last focused tab on close` being enabled. Can you confirm this? 

Thankfully,

~ Robert

**Comment by Bibernull** [comment]
Thanks for looking into it!
I'll check it out as soon as i can.

**Comment by orschiro** [comment]
No rush. 

Thanks @Bibernull!

**Comment by Bibernull** [comment]
with this option on, it can sometimes focus wrong tabs on switch.

i have always wanted this feature in chrome, but seems like i got too used to current behaviour,
that this feature makes it unnatural for me :)

especially when it is buggy like this, it seems like tab IDs from one window, end up in a history array of another window.

everything being async makes this thing difficult, we can't make chrome wait for the script to do it's stuff.

i'll have to think about this, could be it happens when you switch between chrome windows fast.

**Comment by orschiro** [comment]
@Bibernull 

Thanks for giving it another thought! 

I tested your latest release but tabs still do open in background. 

I will if I can reproduce whether this problem is indeed related to switching between tabs too quickly. 

Let me know if I can help you!

~ Robert

**Comment by orschiro** [comment]
Issue solved.
